# Generated by Django 3.1.5 on 2021-04-05 14:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(default=' ', max_length=50)),
                ('board', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=30)),
                ('stand', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('doj', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand', models.CharField(default=' ', max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('mon', models.CharField(max_length=10)),
                ('tues', models.CharField(max_length=10)),
                ('wed', models.CharField(max_length=10)),
                ('thurs', models.CharField(max_length=10)),
                ('fri', models.CharField(max_length=10)),
                ('sat', models.CharField(max_length=10)),
                ('sun', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=40)),
                ('otp', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
